{% set name = "phasorpy" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fe/9e/fd6e2513da42a188183bdff487fed2b5877654a92c99ffc319d19e10092d/phasorpy-{{ version }}.tar.gz
  sha256: 3c01306968575a2b988e68eea034378a791775d16ba22514f99b1ce729f59a49

build:
  number: 0
  skip: true  # [py<312]
  entry_points:
    - phasorpy = phasorpy.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.2.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp       # [linux]
  host:
    - python
    - setuptools >=68.0.0
    - numpy
    - cython >=3.2.0
    - pip
  run:
    - python
    - matplotlib-base >=3.9.0
    - scipy >=1.13.0
    - click
    - pooch
    - tqdm
    - xarray >=2024.6.0
    - tifffile >=2024.8.30
    - ptufile
    - scikit-learn >=1.5.0
    - pawflim
    - liffile
    - fbdfile

test:
  imports:
    - phasorpy
  commands:
    - pip check
    - phasorpy --help
  requires:
    - pip

about:
  home: https://www.phasorpy.org/
  summary: Analysis of luminescence lifetime and hyperspectral images using the phasor approach
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.phasorpy.org/docs/stable/
  dev_url: https://github.com/phasorpy/phasorpy

extra:
  recipe-maintainers:
    - cgohlke
    - bruno-pannunzio
