{% set name = "phasorpy" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/cf/dc/d551932767afb19b32fce553b22a406b4aa749d29976dff1ccaa5f1de880/phasorpy-{{ version }}.tar.gz
  sha256: 1401dd1e474b5ff4aeeb9c455fc23be7c0a02eebcce247c295ba4d1dab62196c

build:
  number: 0
  skip: true  # [py<312]
  entry_points:
    - phasorpy = phasorpy.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.2.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp       # [linux]
  host:
    - python
    - vcomp14  # [win]
    - setuptools >=68.0.0
    - numpy
    - cython >=3.2.0
    - pip
  run:
    - python
    - vcomp14  # [win]
    - matplotlib-base >=3.9.0
    - scipy >=1.13.0
    - click
    - pooch
    - tqdm
    - xarray >=2024.6.0
    - tifffile >=2024.8.30
    - ptufile
    - scikit-learn >=1.5.0
    - pawflim
    - liffile
    - fbdfile
    - czifile >=2026.4.30

test:
  imports:
    - phasorpy
  commands:
    - pip check
    - phasorpy --help
  requires:
    - pip

about:
  home: https://www.phasorpy.org/
  summary: Analysis of luminescence lifetime and hyperspectral images using the phasor approach
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.phasorpy.org/docs/stable/
  dev_url: https://github.com/phasorpy/phasorpy

extra:
  recipe-maintainers:
    - cgohlke
    - bruno-pannunzio
